# Generated by Django 4.1.4 on 2023-01-01 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professor_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='time_added',
        ),
        migrations.AddField(
            model_name='professor',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
