# Generated by Django 4.1.4 on 2023-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_remove_professor_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/professor_images'),
        ),
    ]
